CREATE TABLE IF NOT EXISTS 1_2_1_Arenas (
	ArenaName VARCHAR(50) PRIMARY KEY,
	ArenaState VARCHAR(50) NOT NULL,
	Kit VARCHAR(50) NOT NULL,
	Players INT NOT NULL,
	Server VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS 1_2_1_Teleport (
	PlayerName VARCHAR(50) PRIMARY KEY,
	ArenaName VARCHAR(50) NOT NULL,
	Server VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Stats (
	PlayerUUID VARCHAR(50) PRIMARY KEY,
	PlayerName VARCHAR(50) Not NULL,
	GamesPlayed INT NOT NULL,
	GamesWon INT NOT NULL
);