name: OneVsOne
main: com.github.gamedipoxx.oneVsOne.OneVsOne
author: Professor_Sam
softdepend:
- Multiverse-Core
version: ${project.version}
api-version: 1.17
commands:
   OneVsOne:
      description: Manage OneVsOne
   OneVsOneSetup:
      description: Setup OneVsOne
   leave: 
      description: leave arena
permissions:
   OneVsOne.admin:
      description: Admin permission
   OneVsOne.stats.me:
      description: Stats for yourself
   OneVsOne.stats.other:
      description: View stats from others