name: OneVsOne
main: com.github.gamedipoxx.oneVsOne.OneVsOne
author: Professor_Sam 
softdepend: ['Multiverse-Core']
version: 1.1.1
api-version: 1.17
commands:
   OneVsOne:
      description: "Verwaltet OneVsOne"