CREATE TABLE IF NOT EXISTS Arenas (
	ArenaName VARCHAR(50) PRIMARY KEY,
	ArenaState VARCHAR(50) NOT NULL,
	Kit VARCHAR(50) NOT NULL,
	Players INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Teleport (
	PlayerName VARCHAR(50) PRIMARY KEY,
	ArenaName VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Stats (
	PlayerUUID VARCHAR(50) PRIMARY KEY,
	GamesPlayed INT NOT NULL,
	GamesWon INT NOT NULL
);