name: OneVsOneLobby
main: com.github.gamedipoxx.oneVsOneLobby.OneVsOneLobby
author: Professor_Sam 
version: ${project.version}
api-version: 1.17
commands:
   onevsonelobby:
      description: "Verwaltet die OneVsOneLobby"
   openduelgui:
      description: "a selfmade command to open the duelgui through an npc"
      